### PR TITLE
Go cleaning

### PR DESCRIPTION
**Pull request by chr1sto14**
Saw some Go refactoring opportunities and I got carried away.

* change from https://github.com/gorilla/websocket (archived) to https://github.com/nhooyr/websocket
* bump go version
* piece apart the app into apiclient, poller, pubsub, and server
* add logging about the current number of "subscribers"
* add flags for some configuration
* use json.RawMessage to place parsing timestamps on the client

~~saving this PR as a draft until I have time to add some unit tests.~~

- [x] add tests

### CODE REVIEW

**Comment by chr1sto14** [comment]
@bhelx, I've refactored the Go server for improved readability. I've only tested locally with mock data. I'll ping you on Slack later in the week for the key so I test against live data.

**Comment by chr1sto14** [comment]
Tested with key and ip.

Added a missing poll on startup. 

Should be ready for review, @bhelx

**Comment by bhelx** [comment]
Looking good on my machine. Going to try it out. Thanks again!

**Comment by bhelx** [comment]
It's deployed. Needed a small change to get the image to build: https://github.com/codefornola/nola-transit-map/commit/f80ae67dcfd8112e03455bdc30d8879977832d02

Since this is a pretty big change, please keep an eye on it this week. I'll be testing it out.

**Comment by bhelx** [comment]
Sorry @chr1sto14 I had to revert #10 because the deployed code is the rolled back code. We can't deploy anything until this bug is fixed. I appreciate the refactors, but could we break it up into some smaller PRs? I wasn't able to remove just the piece that introduced the bug.

**Pull request merged**
