### PR TITLE
Nola transit UI updates

### PR DESCRIPTION
**Pull request by AndrewLeach94**
Overhauls the UI with a control bar and modal so users can access everything without needing to swap tabs.

- Revamped bus/streetcar icons will come in another PR.

Map Screen
About Screen

### CODE REVIEW

**Comment by bhelx** [comment]
Looking great! Thanks for putting so much time and attention into this! I think it looks great on large and medium screens but it has a few tweaks needed on mobile.


The about link needs to be shrunk when it crosses the breakpoint. It's covering up the leaflet attribution.

We should also consider giving the select some more space to breath. And I wonder if it's possible to shrink some of it's elements a little too. 

Screen Shot 2022-11-11 at 9 42 47 AM

What do you think @AndrewLeach94 ?

**Comment by AndrewLeach94** [comment]
@bhelx ah yeah for sure it starts getting real wonky applying filters on mobile. I can work on cleaning that up.

**Comment by AndrewLeach94** [comment]
@bhelx good eye. Mobile enhancements are here. Let me know your thoughts. I've removed the label;s for now on mobile but if users express confusion I can open an enhancement later to patch and redesign.
mobile-new

**Comment by bhelx** [comment]
Excellent! Looks good on my machine. Let's deploy it.

**Pull request merged**
